module.exports.users = [
  {
    id: 1,
    name: "Tommye Lopez",
    email: "space1896@gmail.com",
    address: "1083 Mallorca Nene",
    occupation: "Refuse Collector",
    "company info": {
      "company name": "Corsair Memory",
      "business sector": "Professional corporation",
      address: "1207 Jeopardy Private",
      website: "https://una.org/",
    },
  },
  {
    id: 2,
    name: "Earlean Preston",
    email: "downloadable2096@live.com",
    address: "470 Diamond Heights Private",
    occupation: "Midwife",
    "company info": {
      "company name": "Towers Perrin",
      "business sector": "Limited Liability Limited Partnership",
      address: "715 Randall Green",
      website: "https://gives.gu/",
    },
  },
  {
    id: 3,
    name: "Alexis Valencia",
    email: "launches2018@example.org",
    address: "4 Bruce Field",
    occupation: "Carphone Fitter",
    "company info": {
      "company name": "Ecolab",
      "business sector": "Professional corporation",
      address: "326 Standish Extension",
      website: "https://butterfly.name/",
    },
  },
  {
    id: 4,
    name: "Murray Winters",
    email: "gothic2044@live.com",
    address: "340 Medau Stravenue",
    occupation: "Neurologist",
    "company info": {
      "company name": "Informix",
      "business sector": "Professional corporation",
      address: "1032 Kennedy Green",
      website: "https://personal.tours/",
    },
  },
  {
    id: 5,
    name: "Naoma Zimmerman",
    email: "dow1868@live.com",
    address: "240 Ramsel Field",
    occupation: "Nursery Worker",
    "company info": {
      "company name": "AGL Resources",
      "business sector": "Professional corporation",
      address: "1217 Child Run",
      website: "https://describe.vet/",
    },
  },
  {
    id: 6,
    name: "Millard May",
    email: "hockey1981@protonmail.com",
    address: "843 Lysette Bay",
    occupation: "Stage Director",
    "company info": {
      "company name": "The Happy Bear",
      "business sector": "Professional Limited Liability Company",
      address: "1207 Ora Wynd",
      website: "https://deaths.edu/",
    },
  },
  {
    id: 7,
    name: "Noma Mcdowell",
    email: "wyoming1834@yahoo.com",
    address: "1243 Edgar Circle",
    occupation: "Advertising Contractor",
    "company info": {
      "company name": "Hi-Point Firearms",
      "business sector": "Professional Limited Liability Company",
      address: "580 Wright Green",
      website: "https://ist.travel/",
    },
  },
  {
    id: 8,
    name: "Kasha Osborne",
    email: "patterns1809@yahoo.com",
    address: "1227 Bowley Bypass",
    occupation: "Pool Attendant",
    "company info": {
      "company name": "Vizio",
      "business sector": "Professional corporation",
      address: "524 Halleck Stravenue",
      website: "https://norton.helsinki/",
    },
  },
  {
    id: 9,
    name: "Sung Marsh",
    email: "istanbul1956@live.com",
    address: "336 Bay Highway",
    occupation: "Quarry Worker",
    "company info": {
      "company name": "Johnson & Johnson",
      "business sector": "Professional corporation",
      address: "1318 Kendall Run",
      website: "https://treatments.asia/",
    },
  },
  {
    id: 10,
    name: "Teofila Ferrell",
    email: "hide2060@live.com",
    address: "480 Lancaster Field",
    occupation: "Horticulturalist",
    "company info": {
      "company name": "Belle Lady",
      "business sector": "Incorporated",
      address: "436 Hunters Point Square",
      website: "https://page.info/",
    },
  },
];
